### ISSUE TITLE
No class hierarchy

### ISSUE THREAD

**Issue by realh** [sammydre/ts-for-gir#12]
I noticed that all GObject-based classes are exported without parent classes. Instead, all members etc of the parent GObject-class are copied into the definition of the new class. This causes problems when you want to pass one of these classes to a function that expects a parent class.

Is there an important reason you made it do this instead of using extends?

**Comment by nykula** [comment]
Look at #3, we tried to replicate the hierarchy to stop ending up with a gazillion megabytes of typings to parse on every check or IDE launch, but had trouble with static members. TypeScript inheritance and GObject inheritance aren't compatible when it comes to that. Maybe you'll find a fix, please see.

**Comment by realh** [comment]
I've read the comments for #3, but I still don't understand why static method inheritance is a problem. Could you explain that more?

**Comment by nykula** [comment]
When a GObject subclass had a static method with same name and argument count as one in its parent classes, but their argument or return types differed, we got either typings that didn't compile or code that passed type checks but didn't work in Gjs. Unfortunately I don't remember more specifics.

**Comment by realh** [comment]
OK, I see that Typescript doesn't allow even static members to override parents with incompatible types. I'm not very familiar with the language, but I think I've found a workable solution. I haven't tested it yet with any real-world classes from GObject, but a simple test case compiled OK in tsc, and it generated code that did what I expected.

Say what we want is this:

    export class Parent {
        myMethod(): void
        static new(blurb: string): Parent
    }

    export class Child extends Parent {
        myMethod(): void
        static new(blurb1: number, blurb2: number): Child
    }

The compiler rejects that, but accepts it if I simply add this to `Child`:

        static new<T, V>(blurb1: T): V

Surprisingly, I don't need to change `Parent`, which makes things considerably simpler, nor do I have to provide a second argument in the generic method signature. I have to admit I don't know why it's lax about that, but it's good for us. I should probably do some more research on stackoverflow, and also work out what happens if `Parent.new` takes more arguments than `Child.new` instead of the other way round.

Using a generic for the return type actually tightens up type safety, because if you try to abuse it something like this:

    const child = Child.new("blurb")

child would be of type `unknown`, most likely causing errors when we try to use it. The error would be in the wrong place, but that's better than the compiler not detecting the mistake at all.

**Comment by realh** [comment]
Someone on [stackoverflow has thought laterally](https://stackoverflow.com/a/56995123/1541150) and come up with what I think is a great solution. Typescript allows objects and interfaces with the same names to co-exist. The interface provides us with the inheritance relationships and defines instance methods and properties, while the object provides us with the static methods and constructors (and constants?). After a bit of experimentation etc I think this approach will work for us.

**Comment by sammydre** [comment]
Yes, I can confirm the problem is as stated earlier - that TS inheritance and that used in GObject isn't quite compatible.

I did initially use the sort of pattern @realh mentions. Here's a note I made when doing some testing orignally:

``
// Defines an interface for the constructor function itself ("new" is a keyword / special syntax below)
export interface Foo_Constructor {
    new (params: ParamInterface)
}
// Extend the interface with any other static-side methods
// Actually define Foo.new(), not a constructor function
export declare class Foo_Constructor {
    new (a1: string): Foo
}
// The interface/class members
export interface Foo {
    // ...
}
// Describe the "Foo" part of the API: it's the static side of the "Foo" class,
// so "new Foo(params)" gives us a Foo, as does "Foo.new('bar')"
export declare var Foo: Foo_Constructor
``

That was how the generated code looked at one point. I don't remember quite why it changes or why I didn't push this idea forward anymore. Best we can do is implement the approach and see how it goes...

**Comment by realh** [comment]
I started implementing it the way I learned from jcalz's answer on stackoverflow, but I realised that it doesn't solve the problem of having to copy members from superclasses into subclasses. If I don't do that, Typescript doesn't recognise that the objects implement the interfaces. So I think I'll try my first idea instead.

**Comment by JumpLink** [comment]
Is now implemented in the master :)
